In [1]:
!pip install torch

In [2]:
import torch
import numpy as np

In [3]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones([3,4,5])

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [5]:
torch.tensor([[1,2,4,6,8,2],
              [3,5,9,7,5,4],
              [5,8,7,5,1,6]
             ])

tensor([[1, 2, 4, 6, 8, 2],
        [3, 5, 9, 7, 5, 4],
        [5, 8, 7, 5, 1, 6]])

In [6]:
x = torch.tensor([[1,2,4,6,8,2],
              [3,5,9,7,5,4],
              [5,8,7,5,1,6]
             ])

In [7]:
x.shape

torch.Size([3, 6])

In [8]:
x.size()

torch.Size([3, 6])

In [9]:
x[1,1]

tensor(5)

In [10]:
x+10

tensor([[11, 12, 14, 16, 18, 12],
        [13, 15, 19, 17, 15, 14],
        [15, 18, 17, 15, 11, 16]])

In [11]:
x+x

tensor([[ 2,  4,  8, 12, 16,  4],
        [ 6, 10, 18, 14, 10,  8],
        [10, 16, 14, 10,  2, 12]])

In [12]:
torch.log2(x)

tensor([[0.0000, 1.0000, 2.0000, 2.5850, 3.0000, 1.0000],
        [1.5850, 2.3219, 3.1699, 2.8074, 2.3219, 2.0000],
        [2.3219, 3.0000, 2.8074, 2.3219, 0.0000, 2.5850]])

In [13]:
x>3

tensor([[False, False,  True,  True,  True, False],
        [False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False,  True]])

In [14]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

In [15]:
a+b

tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])

In [16]:
a%b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
x[x>3]

tensor([4, 6, 8, 5, 9, 7, 5, 4, 5, 8, 7, 5, 6])

In [18]:
a.dtype

torch.float32

In [19]:
a.int()

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [20]:
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])

In [21]:
x = torch.from_numpy(arr)
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [22]:
x = x.numpy()
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
torch.cuda.is_available()

False

In [24]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [25]:
w = torch.tensor( [[1.,2.],[4.,5.]], requires_grad=True)

function = 10 * torch.log( ( w + 1. ) ).sum()

function.backward()

print(w-w.grad)


tensor([[-4.0000, -1.3333],
        [ 2.0000,  3.3333]], grad_fn=<SubBackward0>)


In [26]:
import numpy as np
X = np.array([[1, 2],
                        [4, 5]])
x_diff = (1 / (X+1))
answer = X - (10 * x_diff)
print(answer)

[[-4.         -1.33333333]
 [ 2.          3.33333333]]
